name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:

    name: Build and public sample site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.13' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Build executable
      run: mix escript.install github bluzky/ego --force
    - name: Build site
      run: ~/.mix/escripts/ego build
    - name: Deploy to target directory
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
